@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "HaseJaeger.Simulator",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1035757024 { 
   	label=Simulationsansicht
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Feldansicht1064985763[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Feldansicht</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   DEHN_FAKTOR: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   feldBreite: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   feldHoehe: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   feldImage: Image [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   g: Graphics [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   groesse: Dimension [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   xFaktor: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   yFaktor: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ paintComponent(g: Graphics)</TD></TR>
<TR><TD ALIGN="LEFT" >+ zeichneMarkierung(x: int, y: int, farbe: Color)</TD></TR>
<TR><TD ALIGN="LEFT" >+ zeichnenVorbereiten()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_278960239 { 
   	label=HaseJaeger
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Feld278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Feld</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   breite: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   feld: Tier[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiefe: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ freieNachbarposition(position: Position): Position</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibBreite(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibObjektAn(position: Position): Tier</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibObjektAn(zeile: int, spalte: int): Tier</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibTiefe(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ nachbarpositionen(position: Position): Iterator</TD></TR>
<TR><TD ALIGN="LEFT" >+ platziere(tier: Tier)</TD></TR>
<TR><TD ALIGN="LEFT" >+ raeumen()</TD></TR>
<TR><TD ALIGN="LEFT" >+ zufaelligeNachbarposition(position: Position): Position</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FeldStatistik278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FeldStatistik</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   zaehler: HashMap [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   zaehlerAktuell: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ erhoeheZaehler(tierklasse: Class)</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibBewohnerInfo(feld: Feld): String</TD></TR>
<TR><TD ALIGN="LEFT" >- gibZaehlerstaende(feld: Feld)</TD></TR>
<TR><TD ALIGN="LEFT" >+ istAktiv(feld: Feld): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ zaehlungBeendet()</TD></TR>
<TR><TD ALIGN="LEFT" >+ zuruecksetzen()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Fuchs278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Fuchs</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   futterLevel: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agiere(aktuellesFeld: Feld, naechstesFeld: Feld, neueTiere: List)</TD></TR>
<TR><TD ALIGN="LEFT" >- alterErhoehen()</TD></TR>
<TR><TD ALIGN="LEFT" >- findeNahrung(feld: Feld, position: Position): Position</TD></TR>
<TR><TD ALIGN="LEFT" >- gebaereNachwuchs(): int</TD></TR>
<TR><TD ALIGN="LEFT" >- hungerVergroessern()</TD></TR>
<TR><TD ALIGN="LEFT" >- kannGebaeren(): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Hase278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Hase</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agiere(feld: Feld, naechstesFeld: Feld, neueTiere: List)</TD></TR>
<TR><TD ALIGN="LEFT" >- alterErhoehen()</TD></TR>
<TR><TD ALIGN="LEFT" >- gebaereNachwuchs(): int</TD></TR>
<TR><TD ALIGN="LEFT" >- kannGebaeren(): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Jaeger278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Jaeger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   schussAnzahl: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agiere(aktuellesFeld: Feld, naechstesFeld: Feld, neueTiere: List)</TD></TR>
<TR><TD ALIGN="LEFT" >- schiessen(feld: Feld)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Position278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Position</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   spalte: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   zeile: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ gibSpalte(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibZeile(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Simulationsansicht278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Simulationsansicht</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   POPULATION_PREFIX: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   SCHRITT_PREFIX: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   farben: HashMap [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   feldansicht: Feldansicht [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   population: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   schrittLabel: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stats: FeldStatistik [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- gibFarbe(tierklasse: Class): Color</TD></TR>
<TR><TD ALIGN="LEFT" >+ istAktiv(feld: Feld): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ zeigeStatus(schritt: int, feld: Feld)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Simulator278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Simulator</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ansicht: Simulationsansicht [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   feld: Feld [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   naechstesFeld: Feld [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   neueTiere: List [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   schritt: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tiere: List [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- bevoelkere(feld: Feld)</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ simuliere(schritte: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ simuliereEinenSchritt()</TD></TR>
<TR><TD ALIGN="LEFT" >+ starteLangeSimulation()</TD></TR>
<TR><TD ALIGN="LEFT" >+ zuruecksetzen()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Tier278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tier</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   alter: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lebendig: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   position: Position [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ agiere(aktuellesFeld: Feld, naechstesFeld: Feld, neueTiere: List)</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibAlter(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibPosition(): Position</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Zaehler278960239[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Zaehler</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   zaehler: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ erhoehen()</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibName(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ gibStand(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ zuruecksetzen()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Feld278960239 -> Tier278960239[label="feld
[0..*]"];
Simulationsansicht278960239 -> FeldStatistik278960239[label="stats
[0..1]"];
Simulationsansicht278960239 -> Feldansicht1064985763[label="feldansicht
[0..1]"];
Simulator278960239 -> Feld278960239[label="feld
[0..1]"];
Simulator278960239 -> Feld278960239[label="naechstesFeld
[0..1]"];
Simulator278960239 -> Simulationsansicht278960239[label="ansicht
[0..1]"];
Simulator278960239 -> Tier278960239[label="simuliereEinenSchritt() -> agiere()"];
Tier278960239 -> Fuchs278960239[arrowhead=none, arrowtail=empty, dir=both];
Tier278960239 -> Hase278960239[arrowhead=none, arrowtail=empty, dir=both];
Tier278960239 -> Jaeger278960239[arrowhead=none, arrowtail=empty, dir=both];
Tier278960239 -> Position278960239[label="position
[0..1]"];
    
}
@enduml